name: Cloudflare Pages

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Code formatting
        run: npm run prettier

      - name: Code linting
        run: npm run lint

      - name: Vitest
        run: npm run test

      - name: Build
        run: npm run build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          projectName: "solid-practice"
          directory: "./dist"
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
