name: Dev build test

on:
  push:
    branches:
      - dev

jobs:
  publish:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Code formatting
        run: npm run prettier

      - name: Code linting
        run: npm run lint

      - name: Vitest
        run: npm run test

      - name: Build
        run: npm run build
